### ISSUE TITLE
[Feature] デザイン追加

### ISSUE THREAD

**Issue by richellin** [dev1and/target#2]
ユーザ（デザイナー）からのFB

**必ず欲しい！**
- https://coliss.com/
- https://photoshopvip.net/
- https://uxmilk.jp/
- https://stocker.jp/diary/
- https://www.webcreatorbox.com/
- https://liginc.co.jp/blog
- https://goodpatch.com/blog

**あったらいいな〜**
- http://creator.dwango.co.jp/
- https://eureka.design/articles
- https://design.visional.inc/
- https://yasuhisa.com/could/
- https://blog.btrax.com/jp/
- https://www.mdn.co.jp/di/contents/
- https://nokojo-foxfound.com/
- https://tomorrowgate.co.jp/blog/
- https://fuyuna.net/category/design

**Comment by pinknanati** [comment]
よろしくお願いします！ 🚀

**Comment by richellin** [comment]
**追加したリスト**: https://github.com/dev1and/target/commit/cb291e94fc2fc735b401c07fa377acdc0087df1c
※ RSSが提供されていなかったり、デザインの関連しない記事が多いものは除外

**デプロイ完了**:  [https://dev1and.com/ja/design](https://dev1and.com/ja/design)

![image](https://user-images.githubusercontent.com/9281881/120111293-559fbe00-c1ac-11eb-85b6-59ef943b6d98.png)
